{{- if and .Values.authService.enabled .Values.authService.secret.enabled (not .Values.authService.secret.existingName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transport.authservice.secretName" . }}
  labels:
    {{- include "transport.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
type: Opaque
stringData:
{{- range $key, $value := .Values.authService.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
