{{- if and .Values.gateway.enabled .Values.backend.enabled .Values.gateway.backendHealthCheckPolicy.enabled }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Values.gateway.backendHealthCheckPolicy.name | quote }}
  labels:
    {{- include "transport.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: {{ .Values.gateway.backendHealthCheckPolicy.requestPath | quote }}
        portSpecification: USE_SERVING_PORT
  targetRef:
    group: ""
    kind: Service
    name: {{ include "transport.backend.fullname" . }}
{{- end }}
