{{- if and .Values.backend.enabled .Values.backend.secret.enabled (not .Values.backend.secret.existingName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transport.backend.secretName" . }}
  labels:
    {{- include "transport.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
{{- range $key, $value := .Values.backend.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
