{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transport.frontend.fullname" . }}
  labels:
    {{- include "transport.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "transport.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "transport.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- $pullSecrets := list -}}
      {{- if .Values.imagePullSecrets }}
      {{- range .Values.imagePullSecrets }}
      {{- $pullSecrets = append $pullSecrets (dict "name" .) -}}
      {{- end }}
      {{- end }}
      {{- if and .Values.imagePullSecret.create .Values.imagePullSecret.name }}
      {{- $pullSecrets = append $pullSecrets (dict "name" .Values.imagePullSecret.name) -}}
      {{- end }}
      {{- if gt (len $pullSecrets) 0 }}
      imagePullSecrets:
        {{- toYaml $pullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}{{- if .Values.frontend.image.tag }}:{{ .Values.frontend.image.tag }}{{- end }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
