{{- if and .Values.imagePullSecret.create .Values.imagePullSecret.name .Values.imagePullSecret.username .Values.imagePullSecret.password }}
{{- $auth := printf "%s:%s" .Values.imagePullSecret.username .Values.imagePullSecret.password | b64enc -}}
{{- $config := dict "auths" (dict .Values.imagePullSecret.registry (dict "username" .Values.imagePullSecret.username "password" .Values.imagePullSecret.password "auth" $auth)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  labels:
    {{- include "transport.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ $config | toJson | quote }}
{{- end }}
