{{- if and .Values.matrixService.enabled .Values.matrixService.secret.enabled (not .Values.matrixService.secret.existingName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transport.matrixservice.secretName" . }}
  labels:
    {{- include "transport.labels" . | nindent 4 }}
    app.kubernetes.io/component: matrix-service
type: Opaque
stringData:
{{- range $key, $value := .Values.matrixService.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
