{{- if and .Values.resourceQuota.enabled (gt (len .Values.resourceQuota.hard) 0) }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceQuota.name | quote }}
  labels:
    {{- include "transport.labels" . | nindent 4 }}
spec:
  hard:
    {{- range $key, $value := .Values.resourceQuota.hard }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
