{{- if and .Values.worker.enabled .Values.worker.secret.enabled (not .Values.worker.secret.existingName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transport.worker.secretName" . }}
  labels:
    {{- include "transport.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
type: Opaque
stringData:
{{- range $key, $value := .Values.worker.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
