apiVersion: v1
kind: Namespace
metadata:
  name: transport-stage
  labels:
    app.kubernetes.io/part-of: transport-optimizer
    env: stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: transport-dev
  labels:
    app.kubernetes.io/part-of: transport-optimizer
    env: dev
